### ISSUE TITLE
Cannot import vistan after pip installing

### ISSUE THREAD

**Issue by mikewojnowicz** [abhiagwl/vistan#1]
importing `vistan` produces an error. 

```
----> 1 import vistan

File ~/Repos/advi/env/lib/python3.9/site-packages/vistan/__init__.py:1, in <module>
----> 1 from .inference import algorithm, recipe

File ~/Repos/advi/env/lib/python3.9/site-packages/vistan/inference.py:7, in <module>
      5 import vistan.vi_families as vi_families
      6 import vistan.objectives as objectives
----> 7 import vistan.interface as interface
      8 import vistan.utilities as utils
      9 import vistan.hyperparams as hyperparams

File ~/Repos/advi/env/lib/python3.9/site-packages/vistan/interface.py:1, in <module>
----> 1 import pystan
      2 import warnings
      3 import pickle
```

I believe I have read that newer versions of pystan should be imported as stan.  I currently have `pystan==3.4.0`.  

Some questions: 

1. What version of python were you using when you built this library?  (In particular, was it python 2 or python 3?) 
2. What version of pystan were you using when you built this library? (I don't see a `requirements.txt`.)
3. What is your recommendation to python3 users for importing your library?  (If it matters, I am using python 3.9.)

**Comment by abhiagwl** [comment]
Hey @mikewojnowicz ! 

I think [this](https://github.com/abhiagwl/vistan/issues/2#issuecomment-1457400528) should solve it.
