### ISSUE TITLE
vistan installation fails when installing PyStan -- need dev environment info

### ISSUE THREAD

**Issue by kgeyer** [abhiagwl/vistan#4]
Hello,

I've had some trouble installing vistan on my laptop (macOS 10.15.7). It fails when it's trying to install pystan. To troubleshoot this, I've tried installing PyStan prior to vistan - and this worked well. However once I install vistan it will uninstall PyStan and fail when it tries to reinstall it. Do you have any recommendations on how to get around this issue? Please let me know if there is any additional information you need to resolve this.

**Comment by kgeyer** [comment]
Hi, 

It looks like the issue I'm having is related to using newer versions of Python and dependent packages:

`vistan 0.0.0.7 requires pystan==2.19.1.1, but you have pystan 3.6.0 which is incompatible.`

What version of Python was used to develop vistan? I believe that this issue can be resolved by using an environment variable with an older version of Python + dependent packages.

**Comment by justindomke** [comment]
Hi there, my understanding is that the pystan interface changed (I think when pystan changed to 3.0?) in a way that broke the way we were interfacing with it. So I wouldn't expect that manually installing a newer version of pystan would work. Instead, could we perhaps figure out what vistan fails to install pystan correctly? I recently tested that with python 3.9 at least, `pip install vistan` does seem to successfully install pystan. (@abhiagwl can you confirm?)

**Comment by abhiagwl** [comment]
Hey @kgeyer!  ``vistan 0.0.0.7`` (and previous version) require ``pystan==2.19.1.1``. As @justindomke mentioned, there were some backward compatibility issues with newer versions of ``pystan>=2.20``. Other users have reported success with ``python 3.8`` and ``python 3.9``. Can you please confirm your issue in a new virtual environment?

**Comment by kgeyer** [comment]
Thank you for your help. I switched to Python 3.9 and could install vistan (plus the demo works).

**Comment by justindomke** [comment]
Great! @abhiagwl could we add a line to the readme saying that using python 3.8 or 3.9 is recommended and that users should not use a newer version of vistan?

We might also want to warn people upon import of VI vistan. Maybe something like below?

```
import sys, warnings
if (sys.version_info.major != 3) or (sys.version_info.minor not in [8,9]):
    warnings.warn("It is recommended to use vistan with python 3.8.x or python 3.9.x")
```
